[package]
name = "css_macros"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
lazy_static = "1"
matches = "0.1"
syn = "1"
proc-macro2 = "1"
darling = "0.10"
proc-quote = "0.3"
heck = "0.3"
