[package]
name = "hobo_derive"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
derive_utils = "0.10"
proc-macro-error = "1"
proc-macro2 = "1"
proc-quote = "0.3"
quote = "1"
syn = "1"
